project:
  name: student-alcohol-consumption
  random_state: 25

paths:
  raw_data: student_mat.csv, student_por.csv
  reports: reports/Reports.pdf

preprocessing:
  drop_columns:
    - 
  target: G3

split:
  test_size: 0.2
  stratify: true

