task: classification

models:
  logistic_regression:
    penalty: l2,
    C: 1.0                  
    solver: lbfgs         
    max_iter: 1000
    class_weight: balanced



  random_forest:
    n_estimators: 300
    max_depth: 10
    min_samples_leaf: 5
    min_samples_split: 10,
    max_features: sqrt
    max_samples: 0.8
    class_weight: balanced
    random_state: 42
  

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc

