task: clustering

features:
  scale: true
  columns:
    - sex
    - studytime
    - failures
    - activities
    - famrel
    - freetime
    - goout
    - Dalc
    - Walc
    - health
    - absences


k_range: [2, 11]

models:
  kmeans:
        n_clusters: 2

  hierarchical_clustering:
        n_clusters: 2,
        linkage: "ward"

evaluation:
  metrics:
    - silhouette
    - elbow



